[workspace]
# Not sure exactly how a workspace should look like, hmm...
#version = "0.1.0"
#authors = ["Per Lindgren <per.lindgren@ltu.se>"]
#edition = "2018"

members = [
    "pass1",
    "pass2",
    "rtic",
    "rtic-lt-examples",
]