[package]
name = "rtic"
version = "0.1.0"
authors = ["Per Lindgren <per.lindgren@ltu.se>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-error = "1"
quote = "1"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "1.0.71"